version: '3.8'

services:
  app:
    build: ./
    restart: always
    ports:
      - "8085:8085"
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: